<a href="https://colab.research.google.com/github/KaueOPG/DCC008---Calculo-Numerico/blob/main/Trabalho2_Lista2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#2° Exercício Computacional - Métodos de Solução de Sistemas Lineares

#Grupo:
1 - Kauê Oliveira Paraízo Garcia - 202265517B

2 - João Pedro Barbosa Coelho - 202369012D

#Pré-requisitos

As seguintes bibliotecas foram instaladas e importadas:

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import scipy

In [ ]:
from numpy.linalg import inv
from numpy.linalg import norm
from numpy import inf
from numpy.linalg import inv

As seguintes funções foram implementadas:

In [ ]:
#função que verifica se a matriz A é ou não diagonal dominante
def diagonal_dominante(A):
  n = A.shape[0]
  alfa = np.zeros(n)
  for i in range(n):
     alfa[i]= np.sum( abs(A[i,:]))/abs(A[i,i])-1
  M=np.max(alfa)
  if M<1:
    return True, M
  else:
    return False, M

In [ ]:
#Calcula a matriz de iteração de Jacobi

def MJ(A):
  D = np.diag(np.diag(A))
  MJ= np.identity(n)-inv(D)@A
  return MJ

In [ ]:
#Calcula a matriz de iteração de Gauss-Seidel

def MS(A):
  D = np.diag(np.diag(A))
  U = np.triu(A)-D
  MS = -inv(A-U)@U
  return MS

In [ ]:
#Calcula a matriz de iteração do método SOR

def MSOR(A, w):
  D = np.diag(np.diag(A))
  U = np.triu(A)-D
  L = A-D-U
  M = inv(D+w*L) @ ((1-w)*D-U)
  return M

In [ ]:
#Calcula a matriz de iteração de Gauss-Seidel

def MS(A):
  D = np.diag(np.diag(A))
  U = np.triu(A)-D
  MS = -inv(A-U)@U
  return MS

In [ ]:
#Calcula a matriz de iteração de Gauss-Seidel

def MS(A):
  D = np.diag(np.diag(A))
  U = np.triu(A)-D
  MS = -inv(A-U)@U
  return MS

In [ ]:
#Calcula a solução pelo método de Jacobi

def xj(A, b, e, N):
  n = A.shape[0]
  D = np.diag(np.diag(A))
  c = inv(D)@b
  x = np.zeros(n)
  iter=0
  er= np.zeros(N)
  for k in range(N):
    iter=iter+1
    x = MJ(A1) @ x+c
    er[k]=np.max(abs(A @x -b))
    if er[k]<e:
      break
  return x, er, iter

In [ ]:
#Calcula a solução pelo método de Gauss-Seidel

def xs(A, b, e, N):
  n = A.shape[0]
  D = np.diag(np.diag(A))
  U = np.triu(A1)-D
  c = inv(A1-U)@b
  x = np.zeros(n)
  iter=0
  er= np.zeros(N)
  for k in range(N):
    iter=iter+1
    x = MS(A1) @ x+c
    er[k]=np.max(abs(A @x -b))
    if er[k]<e:
      break
  return x, er, iter

In [ ]:
#Calcula a solução pelo método SOR

def xsor(A, b, e, N, w):
  n = A.shape[0]
  D = np.diag(np.diag(A))
  U = np.triu(A1)-D
  c = inv(A1-U)@b
  x = np.zeros(n)
  xg = x
  iter=0
  er= np.zeros(N)
  for k in range(N):
    iter=iter+1
    xg = MS(A1) @ xg+c
    x= (1-w)*x+w*xg
    er[k]=np.max(abs(A @x -b))
    if er[k]<e:
      break
  return x, er, iter

#Métodos Iterativos - Exercícios

Para a realização dos seguintes exercícios quatro matrizes esparças de ordem n = 10¹, 10², 10³, 10⁴ e 10^5 na SuiteSparse Matriz Collection que sejam quadradas e não singulares foram escolhidas. Os downloads foram feitos a seguir:

In [ ]:
#Matriz 10¹
!rm *tar.gz
!wget https://suitesparse-collection-website.herokuapp.com/MM/Pothen/mesh1e1.tar.gz
!tar zxvf mesh1e1.tar.gz

In [ ]:
#Matriz 10²
!rm *tar.gz
!wget https://suitesparse-collection-website.herokuapp.com/MM/HB/bcsstm22.tar.gz
!tar zxvf bcsstm22.tar.gz

In [ ]:
#Matriz 10³
!rm *tar.gz
!wget https://suitesparse-collection-website.herokuapp.com/MM/HB/bcsstm08.tar.gz
!tar zxvf bcsstm08.tar.gz

In [ ]:
#Matriz 10⁴
!rm *tar.gz
!wget https://suitesparse-collection-website.herokuapp.com/MM/GHS_indef/bloweybq.tar.gz
!tar zxvf bloweybq.tar.gz

In [ ]:
#Matriz 10^5
!rm *tar.gz
!wget https://suitesparse-collection-website.herokuapp.com/MM/Goodwin/Goodwin_095.tar.gz
!tar zxvf Goodwin_095.tar.gz

1 - A matrize esparçs(S) e densa(A) foram recuperadas dos arquivos pelo código a seguir:

In [ ]:
S1 = scipy.io.mmread('mesh1e1/mesh1e1.mtx')#Matriz 10¹
S2 = scipy.io.mmread('bcsstm22/bcsstm22.mtx')#Matriz 10²
S3 = scipy.io.mmread('bcsstm08/bcsstm08.mtx')#Matriz 10³
S4 = scipy.io.mmread('Pres_Poisson/Pres_Poisson.mtx')#Matriz 10⁴
#S5 = scipy.io.mmread('Goodwin_095/Goodwin_095.mtx')#Matriz 10^5

In [ ]:
A1 =S1.todense('C')
A2 =S2.todense('C')
A3 =S3.todense('C')
A4 =S4.todense('C')
#A5 =S5.todense('C')

2 - Definindo o vetor dos termos independentes b = A.dot(numpy.ones((n,1)):

In [ ]:
b = [5]
n = A1.shape[0]
b.append(A1.dot(np.ones((n,1))))
n = A2.shape[0]
b.append(A2.dot(np.ones((n,1))))
n = A3.shape[0]
b.append(A3.dot(np.ones((n,1))))
n = A4.shape[0]
b.append(A4.dot(np.ones((n,1))))
n = A5.shape[0]
b.append(A5.dot(np.ones((n,1))))
n = A1.shape[0]

3 - Verificação se a matriz pe diagonal dominante:

In [ ]:
teste = diagonal_dominante(A4)
teste

False

4 - Raios Espectrais

In [ ]:
Raio_Jacobi = np.max(abs(np.linalg.eigvals(MJ(A1))))
Raio_Jacobi

0.7779254832691139

In [ ]:
Raio_Gauss= np.max(abs(np.linalg.eigvals(MS(A1))))
Raio_Gauss

5 - Soluções

In [ ]:
%Jacobi

n = A1.shape[0]
u = np.ones((n,1))
b = A1.dot(u)
x, er, iter = xj(A1, b, 0.01, 50)

array([8.20164868, 6.46791993, 4.99515103, 3.89377951, 3.04662249,
       2.38008108, 1.85855852, 1.44999536, 1.13092144, 0.88155538,
       0.68702775, 0.53523061, 0.4169044 , 0.32468564, 0.25288585,
       0.19692692, 0.15333143, 0.11937193, 0.09292533, 0.07233155,
       0.05629799, 0.04381582, 0.03409948, 0.02653657, 0.02065028,
       0.01606912, 0.01250392, 0.00972947, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [ ]:
Erro_Jacobi = np.max(abs(x-u))
Erro_Jacobi

0.0010180376471472519

In [ ]:
#Gauss-Seidel

n = A1.shape[0]
b = A1.dot(np.ones((n,1)))
x, er, iter = xs(A1, b, 0.01, 50)

array([4.14611351, 0.80267842, 0.19319124, 0.02686206, 0.00770099,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [ ]:
Erro_Gauss = np.max(abs(x-u))
Erro_Gauss

0.0036760319050093138

In [ ]:
#SOR

n = A1.shape[0]
b = A1.dot(np.ones((n,1)))
w=1.1
x, er, iter = xsor(A1, b, 0.01, 50, w)
er

array([5.39529851, 1.34882859, 0.34739323, 0.05455321, 0.0064082 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [ ]:
Erro_SOR = np.max(abs(x-u))
Erro_SOR

0.003018567545080897

6 - Ômega ideal

In [ ]:
w=1.1

In [ ]:
import matplotlib
import math

n = A1.shape[0]
u = np.ones((n,1))
b = A1.dot(u)
xj, erj, iterj = xj(A1, b, 0.01, 50)

matplotlib.pyplot.plot( iterj, math.log(erj) )

n = A1.shape[0]
b = A1.dot(np.ones((n,1)))
xs, ers, iters = xs(A1, b, 0.01, 50)

matplotlib.pyplot.plot( iters, math.log(ers) )

n = A1.shape[0]
b = A1.dot(np.ones((n,1)))
xsor, ersor, itersor = xsor(A1, b, 0.01, 50, w)

matplotlib.pyplot.plot( itersor, math.log(ersor) )

matplotlib.pyplot.show()

7 - O método de Jacobi converge se, e somente se, a matriz for diagonal dominante. Se ela for diagonal dominante, o método de Gauss-Seidel irá convergir, mas isso não é necessário, basta que lim n-> inf MS^n[i, k] = 0 para todo i,k. Equivalentemente a norma do máximo de MS é menor que 1, ou também todos os autovalores de MS tem módulo menor que 1. Esse método coverge mais rapido que o de Jacobi, e para um w adequado, o método SOR converge mais rápido que o de Gauss-Seidel.
